/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDR		0x40023800
#define RCC_AHB1ENR_OFFSET 	0x30
#define AHB1ENR_BASE_ADDR	((volatile uint32_t*)( (RCC_BASE_ADDR) + (RCC_AHB1ENR_OFFSET) ))
#define GPIOA_BASE_ADDR 	0x40020000
#define PIN_NUMBER_5		5

typedef struct{
	volatile uint32_t GPIO_MODER;
	volatile uint32_t GPIO_OTYPER;
	volatile uint32_t GPIO_OSPEEDR;
	volatile uint32_t GPIO_PUPDR;
	volatile uint32_t GPIO_IDR;
	volatile uint32_t GPIO_ODR;
	volatile uint32_t GPIO_BSRR;
	volatile uint32_t GPIO_LCKR;
	volatile uint32_t GPIO_AF[2];
} GPIO_Typdef_t;

#define GPIOA ((GPIO_Typdef_t*)GPIOA_BASE_ADDR)

void gpio_toggle_pin(GPIO_Typdef_t* GPIOx, uint16_t pin_number);

int main(void)
{
	*AHB1ENR_BASE_ADDR |= 1;
	GPIOA->GPIO_MODER &= ~(3 << (PIN_NUMBER_5 * 2));
	GPIOA->GPIO_MODER |=  (1 << (PIN_NUMBER_5 * 2));


	while (1){
		// GPIOA->GPIO_ODR |=  1 << PIN_NUMBER_5;
		gpio_toggle_pin(GPIOA, PIN_NUMBER_5);

	}
    /* Loop forever */
	for(;;);
}

void gpio_toggle_pin(GPIO_Typdef_t* GPIOx, uint16_t pin_number){
	if (( GPIOx->GPIO_IDR & (1 <<pin_number) ) != 0){
		GPIOx->GPIO_ODR &= ~(1 << pin_number);
		for (volatile int i = 0; i < 500000; ++i);
	}

	else{
		GPIOx->GPIO_ODR |= 1 << pin_number;
		for (volatile int i = 0; i < 500000; ++i);
	}

}
